### ISSUE TITLE
 ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Curryifgou** [MIC-DKFZ/HD-BET#38]
Hello!
When I run this code, there are some mistakes.
`Downloading https://zenodo.org/record/2540695/files/0.model?download=1 ...
Traceback (most recent call last):
  File "/software/anaconda3/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/software/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/software/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/software/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/software/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/software/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/software/anaconda3/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/software/anaconda3/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/software/anaconda3/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/software/anaconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
`

I want to know how to solve it, thank you very much!

**Comment by sun5030** [comment]
Hello, may I ask if your issue has been resolved? If so, how was it resolved? I encountered the same problem @Curryifgou

**Comment by yibingchen2023** [comment]
I encountered the same problem, how to solve it, thanks!
