### ISSUE TITLE
ModuleNotFoundError: No module named 'imp' with Python v3.12

### ISSUE THREAD

**Issue by appukuttan-shailesh** [MIC-DKFZ/HD-BET#58]
The `imp` module has been removed in Python3.12 in favor of importlib.
Ref: https://docs.python.org/3.11/library/imp.html
> Deprecated since version 3.4, will be removed in version 3.12: The [imp](https://docs.python.org/3.11/library/imp.html#module-imp) module is deprecated in favor of [importlib](https://docs.python.org/3.11/library/importlib.html#module-importlib).

Currently this throws the following error:
> Traceback (most recent call last):
  File "/home/sappukuttan/miniconda3/bin/hd-bet", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/<<PATH>>/HD-BET/HD_BET/hd-bet", line 4, in <module>
    from HD_BET.run import run_hd_bet
  File "/<<PATH>>/HD-BET/HD_BET/run.py", line 6, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

**Comment by andersenthomas** [comment]
Is this open? I'm currently facing the same issue.

**Comment by andersenthomas** [comment]
Excellent. Thank you. Will test asap.

All the best,
Thomas

---
Thomas Lund Andersen
@ ***@***.***
http://thomasandersen.dk

-------- Oprindelig besked --------
17.10.2024 14.51, Fabian Isensee  skrev:
